defaults:
  - config_default

# Training parameters
num_epochs: 20

# Log settings
log_freq: 1
eval_freq: 10
save_freq: 100

# Model paths
basepath: data/optic_thermal/Images/test-dev
output_path: results

# System settings
wandb_online: false