# Training parameters
batch_size: 2
lr: 1e-5
num_epochs: 1000
decay_rate: 0.5
loss_scale: 100
ent_scale: 1.0
cons_scale: 1.0
grad_iter: 0

# Log settings
log_freq: 10
eval_freq: 50
save_freq: 200

# Dataset settings
dataset: turbines_OT
with_rgb: false
num_frames: 3
num_t: 1
gap: 2

# Model paths
basepath: data/optic_thermal/Images/trainval
output_path: results
dino_path: models/dino_deitsmall8_pretrain_full_checkpoint.pth
resume_path: null

# System settings
seed: 0
verbose: null
device: cuda
world_size: 1
local_rank: -1
dist_on_itp: false
dist_url: env://
wandb_online: true