defaults:
  - config_default

# Training parameters
num_epochs: 250

# Log settings
log_freq: 10
eval_freq: 50
save_freq: 200

# Model paths
basepath: data/optic_thermal/Images/trainval
output_path: results

# System settings
wandb_online: true